[package]
name = "gbaemu-core"
version = "0.1.0"
edition = "2024"

[dependencies]
armv4t_emu = "0.1.2"
colorable = "0.1.4"
image = "0.25.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json5 = "0.2.1"
stackvec = { version = "0.1.0", path = "../stackvec" }
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.64"
